-- MySQL Script generated by MySQL Workbench
-- ter 12 nov 2019 18:07:30 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema techtravelbrazil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techtravelbrazil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techtravelbrazil` DEFAULT CHARACTER SET utf8 ;
USE `techtravelbrazil` ;

-- -----------------------------------------------------
-- Table `techtravelbrazil`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtravelbrazil`.`usuario` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  `senha` VARCHAR(100) NULL,
  PRIMARY KEY (`cod_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtravelbrazil`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtravelbrazil`.`link` (
  `cod_link` INT NOT NULL AUTO_INCREMENT,
  `des_link` VARCHAR(100) NULL,
  `url_link` VARCHAR(100) NULL,
  `cod_usuario` INT NOT NULL,
  PRIMARY KEY (`cod_link`),
  INDEX `fk_link_usuario1_idx` (`cod_usuario` ASC),
  CONSTRAINT `fk_link_usuario1`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `techtravelbrazil`.`usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtravelbrazil`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtravelbrazil`.`evento` (
  `cod_evento` INT NOT NULL AUTO_INCREMENT,
  `des_evento` VARCHAR(100) NULL,
  `dat_inicial` DATE NULL,
  `dat_final` DATE NULL,
  `hor_inicial` TIME NULL,
  `hor_final` TIME NULL,
  `conteudo` TEXT NULL,
  `cod_usuario` INT NOT NULL,
  `link_cod_link` INT NOT NULL,
  PRIMARY KEY (`cod_evento`),
  INDEX `fk_evento_usuario_idx` (`cod_usuario` ASC),
  INDEX `fk_evento_link1_idx` (`link_cod_link` ASC),
  CONSTRAINT `fk_evento_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `techtravelbrazil`.`usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_link1`
    FOREIGN KEY (`link_cod_link`)
    REFERENCES `techtravelbrazil`.`link` (`cod_link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtravelbrazil`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtravelbrazil`.`livro` (
  `cod_livro` INT NOT NULL AUTO_INCREMENT,
  `tit_livro` VARCHAR(100) NULL,
  `autores` VARCHAR(100) NULL,
  `conteudo` TEXT NULL,
  `cod_usuario` INT NOT NULL,
  `link_cod_link` INT NOT NULL,
  PRIMARY KEY (`cod_livro`),
  INDEX `fk_livro_usuario1_idx` (`cod_usuario` ASC),
  INDEX `fk_livro_link1_idx` (`link_cod_link` ASC),
  CONSTRAINT `fk_livro_usuario1`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `techtravelbrazil`.`usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_link1`
    FOREIGN KEY (`link_cod_link`)
    REFERENCES `techtravelbrazil`.`link` (`cod_link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtravelbrazil`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtravelbrazil`.`local` (
  `cod_local` INT NOT NULL AUTO_INCREMENT,
  `des_local` VARCHAR(100) NULL,
  `conteudo` TEXT NULL,
  `cod_usuario` INT NOT NULL,
  `link_cod_link` INT NOT NULL,
  PRIMARY KEY (`cod_local`),
  INDEX `fk_local_usuario1_idx` (`cod_usuario` ASC),
  INDEX `fk_local_link1_idx` (`link_cod_link` ASC),
  CONSTRAINT `fk_local_usuario1`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `techtravelbrazil`.`usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local_link1`
    FOREIGN KEY (`link_cod_link`)
    REFERENCES `techtravelbrazil`.`link` (`cod_link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techtravelbrazil`.`acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techtravelbrazil`.`acesso` (
  `cod_link` INT NOT NULL,
  `data` DATE NOT NULL,
  `qtde` INT NULL,
  INDEX `fk_acesso_link1_idx` (`cod_link` ASC),
  PRIMARY KEY (`cod_link`, `data`),
  CONSTRAINT `fk_acesso_link1`
    FOREIGN KEY (`cod_link`)
    REFERENCES `techtravelbrazil`.`link` (`cod_link`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
